name: Backend Deployment

on:
  push:
    branches: [ main, holidayfeatures ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
  pull_request:
    branches: [ main, holidayfeatures ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # Create SSH key file
          echo "$PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          
          # Copy files to EC2
          scp -i deploy_key -o StrictHostKeyChecking=no -r backend/* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/holidayplanner/backend/
          
          # Execute deployment commands on EC2
          ssh -i deploy_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} '
            cd /home/ubuntu/holidayplanner/backend
            npm ci
            pm2 restart holidayplanner-backend || pm2 start server.js --name holidayplanner-backend
          '
          
          # Clean up
          rm deploy_key 