name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    branches: [main, develop]
    types: 
      - completed

jobs:
  deploy-staging:
    name: Deploy to Staging
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Debug Staging Secrets
        run: |
          if [ -z "${{ secrets.STAGING_HOST }}" ]; then
            echo "::error::STAGING_HOST secret is not set"
            exit 1
          else
            echo "STAGING_HOST secret is set"
          fi
          if [ -z "${{ secrets.SSH_USERNAME }}" ]; then
            echo "::error::SSH_USERNAME secret is not set"
            exit 1
          else
            echo "SSH_USERNAME secret is set"
          fi
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "::error::SSH_PRIVATE_KEY secret is not set"
            exit 1
          else
            echo "SSH_PRIVATE_KEY secret is set"
          fi
          
      - name: Install Dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install
          
      - name: Build for Production
        run: |
          cd frontend
          npm run build
          
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/holidayplanner
            git pull origin develop
            cd backend
            npm install
            pm2 restart holidayplanner-api
            cd ../frontend
            npm install
            npm run build
            
      - name: Health Check
        run: |
          echo "Performing health check on staging environment..."
          curl -sSf http://${{ secrets.STAGING_HOST }}/status || (echo "Health check failed" && exit 1)
            
      - name: Run Integration Tests in Staging
        run: |
          echo "Running integration tests in staging environment"
          # Add your integration test commands here
          
      - name: Run Performance Tests
        run: |
          echo "Running performance tests in staging environment"
          # Add your performance test commands here
          
  deploy-production:
    name: Deploy to Production
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://13.236.135.130/
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Debug Secrets
        run: |
          if [ -z "${{ secrets.PRODUCTION_HOST }}" ]; then
            echo "::error::PRODUCTION_HOST secret is not set"
            exit 1
          else
            echo "PRODUCTION_HOST secret is set"
          fi
          if [ -z "${{ secrets.SSH_USERNAME }}" ]; then
            echo "::error::SSH_USERNAME secret is not set"
            exit 1
          else
            echo "SSH_USERNAME secret is set"
          fi
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "::error::SSH_PRIVATE_KEY secret is not set"
            exit 1
          else
            echo "SSH_PRIVATE_KEY secret is set"
          fi
          
      - name: Install Dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install
          
      - name: Build for Production
        run: |
          cd frontend
          npm run build
          
      - name: Prepare Blue Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /var/www/holidayplanner-blue
            
      - name: Deploy to Blue Environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/holidayplanner-blue
            git pull origin main
            cd backend
            npm install
            cd ../frontend
            npm install
            npm run build
            
      - name: Switch to Blue Environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www
            rm -rf holidayplanner-green
            mv holidayplanner holidayplanner-green
            mv holidayplanner-blue holidayplanner
            cd holidayplanner/backend
            pm2 restart holidayplanner-api
            
      - name: Verify Deployment
        run: |
          echo "Verifying deployment..."
          curl -sSf http://13.236.135.130/ || (echo "Deployment verification failed, rolling back" && exit 1)
          
      - name: Health Check
        run: |
          echo "Performing health check on production environment..."
          curl -sSf http://13.236.135.130/status || (echo "Health check failed" && exit 1)
          
      - name: Rollback on Failure
        if: failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www
            rm -rf holidayplanner-blue
            mv holidayplanner holidayplanner-blue
            mv holidayplanner-green holidayplanner
            cd holidayplanner/backend
            pm2 restart holidayplanner-api 